### ISSUE TITLE
Please update gnome bookmark file path

### ISSUE THREAD

**Issue by QiangF** [kuanyui/fm-bookmarks.el#3]
Hello,
The path to gnome bookmarks seem to have been changed.
See http://askubuntu.com/questions/192747/where-does-nautilus-stores-bookmark-names

**Comment by kuanyui** [comment]
fm-bookmarks exactly supported GNOME3 Nautilus (`~/.config/gtk-3.0/bookmarks`), take a look:

https://github.com/kuanyui/fm-bookmarks.el/blob/master/fm-bookmarks.el#L175

Maybe it's your Nautilus too old?

**Comment by QiangF** [comment]
Thank you for the link. Turns out fm-bookmarks is complaining missing files for some of the file managers, after deleting everything else with only gnome3 left in fm-bookmarks-enabled-file-managers, it works fantastically.
